//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LogicielNettoyagePC.UI {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceFR {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceFR() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("LogicielNettoyagePC.UI.ResourceFR", typeof(ResourceFR).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        public static string AddBtnTxt {
            get {
                return ResourceManager.GetString("AddBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyse en cours ....
        /// </summary>
        public static string AnalysisInProgressTxt {
            get {
                return ResourceManager.GetString("AnalysisInProgressTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyser.
        /// </summary>
        public static string AnalyzeBtnTxt {
            get {
                return ResourceManager.GetString("AnalyzeBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analyseur.
        /// </summary>
        public static string Analyzer {
            get {
                return ResourceManager.GetString("Analyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ! Attention, pour fonctionner, le logiciel doit être lancé en mode administrateur..
        /// </summary>
        public static string AttantionTxt {
            get {
                return ResourceManager.GetString("AttantionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        public static string CancelBtnTxt {
            get {
                return ResourceManager.GetString("CancelBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Impossible de fermer l&apos;application..
        /// </summary>
        public static string CantCloseApplicationTxt {
            get {
                return ResourceManager.GetString("CantCloseApplicationTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nettoyer.
        /// </summary>
        public static string CleanBtnTxt {
            get {
                return ResourceManager.GetString("CleanBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nettoyage en cours ....
        /// </summary>
        public static string CleaningInProgressTxt {
            get {
                return ResourceManager.GetString("CleaningInProgressTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermeture de l&apos;application.
        /// </summary>
        public static string CloseApplicationTxt {
            get {
                return ResourceManager.GetString("CloseApplicationTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright 2021 PinkPantera.
        /// </summary>
        public static string CopyrightTxt {
            get {
                return ResourceManager.GetString("CopyrightTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer le dossier de cette liste.
        /// </summary>
        public static string DeleteFolder {
            get {
                return ResourceManager.GetString("DeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Echec de l&apos;ajout du dossier.
        /// </summary>
        public static string DirectoryAddedFail {
            get {
                return ResourceManager.GetString("DirectoryAddedFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du dossier.
        /// </summary>
        public static string DirectoryNameTxt {
            get {
                return ResourceManager.GetString("DirectoryNameTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ??? Mb.
        /// </summary>
        public static string EmptyMb {
            get {
                return ResourceManager.GetString("EmptyMb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        public static string ExitBtnTxt {
            get {
                return ResourceManager.GetString("ExitBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le dossier n&apos;est pas valide.
        /// </summary>
        public static string FolderInvalid {
            get {
                return ResourceManager.GetString("FolderInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historique.
        /// </summary>
        public static string HistoricBtnTxt {
            get {
                return ResourceManager.GetString("HistoricBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Historique.
        /// </summary>
        public static string HistoryPageCaptionTxt {
            get {
                return ResourceManager.GetString("HistoryPageCaptionTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accueil.
        /// </summary>
        public static string HomePageTitle {
            get {
                return ResourceManager.GetString("HomePageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dernière analyse: .
        /// </summary>
        public static string LastAnalysisTxt {
            get {
                return ResourceManager.GetString("LastAnalysisTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liste des dossiers à traiter.
        /// </summary>
        public static string ListDirectoriesToProcessTxt {
            get {
                return ResourceManager.GetString("ListDirectoriesToProcessTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour nettoyer votre ordinateur il faut choisir le menu «Analyseur». En  y cliquant sur le bouton « Analyser» vous aurez le détail des éléments à nettoyer. Clique sur le bouton « Nettoyer » et effectue le nettoyage..
        /// </summary>
        public static string ManualAnalyseTxt {
            get {
                return ResourceManager.GetString("ManualAnalyseTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vous pouvez visualiser l&apos;historique de nettoyage via la rubrique « Historique ». Vous y verrez l’information sur les dix derniers nettoyages..
        /// </summary>
        public static string ManualHistoryTxt {
            get {
                return ResourceManager.GetString("ManualHistoryTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Le menu « Options » vous permettra de modifier la liste des dossiers à traiter..
        /// </summary>
        public static string ManualOptionsTxt {
            get {
                return ResourceManager.GetString("ManualOptionsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Navigateur.
        /// </summary>
        public static string NavigatorTxt {
            get {
                return ResourceManager.GetString("NavigatorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pour effacer votre ordinateur des fichiers temporaires, cliquez sur &quot;Nettoyer&quot;.
        /// </summary>
        public static string NeedToCleanTxt {
            get {
                return ResourceManager.GetString("NeedToCleanTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jamais.
        /// </summary>
        public static string NeverTxt {
            get {
                return ResourceManager.GetString("NeverTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouveau.
        /// </summary>
        public static string NewBtnTxt {
            get {
                return ResourceManager.GetString("NewBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir dans le navigateur externe.
        /// </summary>
        public static string OpenURLInExternalNavigatorTxt {
            get {
                return ResourceManager.GetString("OpenURLInExternalNavigatorTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emplacement.
        /// </summary>
        public static string PathTxt {
            get {
                return ResourceManager.GetString("PathTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effectuez l&apos;analyse en cliquant sur &quot;Analyser&quot;.
        /// </summary>
        public static string PerformAnalysisTxt {
            get {
                return ResourceManager.GetString("PerformAnalysisTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETTOYAGE PC est un logiciel qui nettoie votre PC et libérez de l&apos;espace sur votre disque..
        /// </summary>
        public static string PresentationText {
            get {
                return ResourceManager.GetString("PresentationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Il y a un processus en cours..
        /// </summary>
        public static string ProcessInProgressTxt {
            get {
                return ResourceManager.GetString("ProcessInProgressTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Résultats de l&apos;analyse.
        /// </summary>
        public static string ResultsOfAnalise {
            get {
                return ResourceManager.GetString("ResultsOfAnalise", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner tous.
        /// </summary>
        public static string SelectAll {
            get {
                return ResourceManager.GetString("SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionner.
        /// </summary>
        public static string SelectBtnTxt {
            get {
                return ResourceManager.GetString("SelectBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sélectionnez des éléments à nettoyer.
        /// </summary>
        public static string SelectResourcesrToCleanTxt {
            get {
                return ResourceManager.GetString("SelectResourcesrToCleanTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string SettingsTxt {
            get {
                return ResourceManager.GetString("SettingsTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site-Web.
        /// </summary>
        public static string SiteBtnTxt {
            get {
                return ResourceManager.GetString("SiteBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total espace à nettoyer:.
        /// </summary>
        public static string SpaceToCleanTxt {
            get {
                return ResourceManager.GetString("SpaceToCleanTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Analise du PC nécessaire.
        /// </summary>
        public static string TopTitle {
            get {
                return ResourceManager.GetString("TopTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mis à jour.
        /// </summary>
        public static string UpdateBtnTxt {
            get {
                return ResourceManager.GetString("UpdateBtnTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/PinkPantera/PC-Cleaner.
        /// </summary>
        public static string UrlTxt {
            get {
                return ResourceManager.GetString("UrlTxt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NETTOYAGE PC.
        /// </summary>
        public static string WindowTitle {
            get {
                return ResourceManager.GetString("WindowTitle", resourceCulture);
            }
        }
    }
}
